name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thank you for contributing to candlestick. Feel free to report any issue or ask for new features.'
        pr-message: 'Thank you very much for your meaningful contribution. We will review it as soon as possible.'
